Repository wso2/vscode-extensions, pull requests merged in 2025-09, with the labels that each got.

#344 Avoid sourcemaps in production build
  workspaces/ballerina/ballerina-extension/webpack.config.js
  workspaces/ballerina/ballerina-visualizer/webpack.config.js
  workspaces/ballerina/persist-layer-diagram/webpack.config.js
  workspaces/ballerina/type-diagram/webpack.config.js
  workspaces/bi/bi-extension/webpack.config.js
  workspaces/choreo/choreo-extension/webpack.config.js
  workspaces/choreo/choreo-webviews/webpack.config.js
  workspaces/mi/mi-extension/webpack.config.js
  workspaces/wso2-platform/wso2-platform-extension/webpack.config.js
  workspaces/wso2-platform/wso2-platform-webviews/webpack.config.js
Labels: Checks/Run with UI Tests

#501 Run release workflow in codebuild runner
  .github/workflows/publish-vsix.yml
  .github/workflows/release-vsix.yml
Labels: Runner/AWS

#511 [BI & MI Data Mappers] Fix positioning mapping options widget for root input,output mappings
  workspaces/ballerina/data-mapper/src/components/Diagram/OverriddenLinkLayer/LabelWidget.tsx
  workspaces/mi/mi-data-mapper/src/components/Diagram/OverriddenLinkLayer/LabelWidget.tsx
Labels: Runner/AWS

#512 Fix record config popup crops the content
  workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/Views/RecordConfigView.tsx
  workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/index.tsx
Labels: Runner/AWS

#513 Sync with quick-merge and fix windows path issue
  workspaces/ballerina/ballerina-extension/src/views/visualizer/activate.ts
  workspaces/ballerina/data-mapper/src/components/DataMapper/DataMapperEditor.tsx
  workspaces/ballerina/data-mapper/src/components/DataMapper/Header/DataMapperHeader.tsx
  workspaces/common-libs/ui-toolkit/src/components/ExpressionEditor/components/Header/ExpressionEditor.tsx
Labels: Runner/AWS

#514 Update fileName prop in AI Agent ConfigForm component to use the correct filename
  workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/NewAgent.tsx
Labels: Runner/AWS

#490 Add minor UI fixes
  workspaces/ballerina/ballerina-side-panel/src/components/NodeList/index.tsx
  workspaces/ballerina/type-editor/src/TypeHelper/TypeBrowser.tsx
Labels: Runner/AWS

#556 Fix DS resource generation table scrolling issue
  workspaces/mi/mi-visualizer/src/components/Table/index.tsx
Labels: Extension/MI

#548 Fix issues in the MI Extension
  workspaces/mi/mi-core/src/rpc-types/mi-visualizer/types.ts
  workspaces/mi/mi-extension/src/rpc-managers/mi-diagram/rpc-manager.ts
  workspaces/mi/mi-extension/src/rpc-managers/mi-visualizer/rpc-manager.ts
  workspaces/mi/mi-visualizer/src/views/Diagram/InboundEndpoint.tsx
  workspaces/mi/mi-visualizer/src/views/Forms/APIform/index.tsx
  workspaces/mi/mi-visualizer/src/views/Overview/ProjectInformation/ProjectInformationForm.tsx
Labels: Extension/MI
