Repository wso2/vscode-extensions, pull requests merged in 2025-10, with the labels that each got.

#522 Add Feedback Functionality for MI Copilot
  workspaces/mi/mi-core/src/rpc-types/mi-diagram/index.ts
  workspaces/mi/mi-core/src/rpc-types/mi-diagram/rpc-type.ts
  workspaces/mi/mi-core/src/rpc-types/mi-diagram/types.ts
  workspaces/mi/mi-extension/.env.example
  workspaces/mi/mi-extension/src/rpc-managers/mi-diagram/rpc-handler.ts
  workspaces/mi/mi-extension/src/rpc-managers/mi-diagram/rpc-manager.ts
  workspaces/mi/mi-rpc-client/src/rpc-clients/mi-diagram/rpc-client.ts
  workspaces/mi/mi-visualizer/src/views/AIPanel/component/AIChatMessage.tsx
  workspaces/mi/mi-visualizer/src/views/AIPanel/component/FeedbackBar/index.tsx
  workspaces/mi/mi-visualizer/src/views/AIPanel/component/FeedbackDialog/index.tsx
  workspaces/mi/mi-visualizer/src/views/AIPanel/component/MICopilotContext.tsx
  workspaces/mi/mi-visualizer/src/views/AIPanel/component/feedbackUtils.ts
  workspaces/mi/mi-visualizer/src/views/AIPanel/component/useFeedback.ts
  workspaces/mi/mi-visualizer/src/views/AIPanel/types.ts
Labels: Extension/MI

#529 Add authentication prompt for AI related features
  workspaces/mi/mi-diagram/src/components/nodes/ReferenceNode/ReferenceNodeModel.ts
  workspaces/mi/mi-visualizer/src/MainPanel.tsx
  workspaces/mi/mi-visualizer/src/PopupPanel.tsx
  workspaces/mi/mi-visualizer/src/components/AuthenticationDialog/AuthenticationDialog.tsx
  workspaces/mi/mi-visualizer/src/components/AuthenticationDialog/index.ts
  workspaces/mi/mi-visualizer/src/components/AuthenticationDialog/useAuthentication.ts
  workspaces/mi/mi-visualizer/src/views/Forms/DataMapperMigrationForm.tsx
  workspaces/mi/mi-visualizer/src/views/Forms/Tests/TestCaseForm.tsx
  workspaces/mi/mi-visualizer/src/views/Forms/Tests/TestSuiteForm.tsx
Labels: Extension/MI

#273 Improve API form with per API CORs settings
  workspaces/mi/mi-visualizer/src/views/Forms/APIform/index.tsx
Labels: Extension/MI

#572 Fix intermittent test failures of dependency manager
  workspaces/mi/mi-extension/src/test/e2e-playwright-tests/components/Overview.ts
  workspaces/mi/mi-visualizer/src/views/Overview/ProjectInformation/DependencyItem.tsx
Labels: Runner/AWS

#567 Add snapshot tests for component-diagram package
  common/config/rush/pnpm-lock.yaml
  workspaces/ballerina/component-diagram/babel.config.js
  workspaces/ballerina/component-diagram/jest.config.js
  workspaces/ballerina/component-diagram/package.json
  workspaces/ballerina/component-diagram/src/components/Diagram.tsx
  workspaces/ballerina/component-diagram/src/resources/icons/nodes/ListenIcon.tsx
  workspaces/ballerina/component-diagram/src/stories/1-empty.json
  workspaces/ballerina/component-diagram/src/stories/1-start.json
  workspaces/ballerina/component-diagram/src/stories/2-no-cons.json
  workspaces/ballerina/component-diagram/src/stories/2-only-automation.json
  workspaces/ballerina/component-diagram/src/stories/3-no-service.json
  workspaces/ballerina/component-diagram/src/stories/3-simple-service.json
  workspaces/ballerina/component-diagram/src/stories/4-multiple-services.json
  workspaces/ballerina/component-diagram/src/stories/4-sample.json
  workspaces/ballerina/component-diagram/src/stories/5-connection-complex.json
  workspaces/ballerina/component-diagram/src/stories/6-ai-agent-complex.json
  workspaces/ballerina/component-diagram/src/stories/7-graphql-complex.json
  workspaces/ballerina/component-diagram/src/stories/8-multiple-connections-complex.json
  workspaces/ballerina/component-diagram/src/stories/Diagram.stories.tsx
  workspaces/ballerina/component-diagram/src/test/Diagram.test.tsx
  workspaces/ballerina/component-diagram/src/test/__snapshots__/Diagram.test.tsx.snap
  workspaces/ballerina/component-diagram/src/test/jest.env.ts
  workspaces/ballerina/component-diagram/src/test/matchMedia.ts
Labels: Runner/AWS

#590 Fix E2E tests
  workspaces/mi/mi-extension/src/test/e2e-playwright-tests/components/ArtifactTest/APITests.ts
Labels: Extension/MI, Checks/Run MI UI Tests

#566 Fix issue in expression editor
  workspaces/common-libs/ui-toolkit/src/components/ExpressionEditor/components/Token/index.tsx
  workspaces/common-libs/ui-toolkit/src/components/ExpressionEditor/types/token.ts
  workspaces/common-libs/ui-toolkit/src/components/ExpressionEditor/utils/token.ts
  workspaces/mi/mi-diagram/src/components/Form/FormGenerator.tsx
  workspaces/mi/mi-diagram/src/components/Form/FormTokenEditor/index.tsx
Labels: Extension/MI

#587 Add advanced parameters in resource form, update undo-redo icons and fix service navigation
  workspaces/ballerina/ballerina-core/src/state-machine-types.ts
  workspaces/ballerina/ballerina-extension/src/RPCLayer.ts
  workspaces/ballerina/ballerina-extension/src/stateMachine.ts
  workspaces/ballerina/ballerina-extension/src/utils/state-machine-utils.ts
  workspaces/ballerina/ballerina-visualizer/src/components/Skeletons/TitleBarSkeleton.tsx
  workspaces/ballerina/ballerina-visualizer/src/components/TitleBar/index.tsx
  workspaces/ballerina/ballerina-visualizer/src/components/UndoRedoGroup/index.tsx
  workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/index.tsx
  workspaces/ballerina/ballerina-visualizer/src/views/BI/ServiceDesigner/Forms/ResourceForm/Parameters/Parameters.tsx
  workspaces/common-libs/font-wso2-vscode/src/icons/bi-redo.svg
  workspaces/common-libs/font-wso2-vscode/src/icons/bi-undo.svg
Labels: Runner/AWS
